### ISSUE TITLE
01Space_ESP32-C3-RGB : LED config broken

### ISSUE THREAD

**Issue by Noschvie** [tasmota/autoconf#20]
The WS2812 / onboard LED doesn't work with GPIO8 as configured by "01Space_ESP32-C3-RGB" 

![image](https://user-images.githubusercontent.com/48217146/212563243-ba9e0e3e-86e8-4061-bedc-79d742e5968d.png)

Using GPIO7 instead as shown by the screenshot let the onboard LED working.

**Comment by sfromis** [comment]
Is there more than one board variant? I have the [ESP32-C3FH4-RGB](https://github.com/01Space/ESP32-C3FH4-RGB/) working with the pin config suggested on that page, which includes the WS2812B 5x5 matrix on gpio 8, as in the template included in autoconf, which is the same pin layout as in the Tasmota templates repository for [01space 5x5 WS2812B Development Board (ESP32-C3-RGB)](https://templates.blakadder.com/01space_ESP32-C3-RGB.html).

**Comment by Jason2866** [comment]
Closing since the config is verified working for the board
