### ISSUE TITLE
Some fixes needed for Shelly Mini Gen3

### ISSUE THREAD

**Issue by tbrasser** [tasmota/autoconf#37]
We're pretty close though!

Getting this in the console when trying to migrate:

```
17:11:32.444 RSL: RESULT = {"OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32c3.bin"}
17:12:19.564 RSL: RESULT = {"OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32c3.bin"}
17:12:24.640 UPL: Step 1 Done
17:12:24.645 UPL: Starting step 2
17:12:24.726 UPL: flashing `safeboot` from http://ota.tasmota.com/tasmota32/release/tasmota32c3-safeboot.bin 712kB
17:12:24.727 UPL: error (internal_error) `app0` offset is not 0x10000
17:14:59.556 RSL: RESULT = {"OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32c3.bin"}
17:15:32.380 RSL: RESULT = {"OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32c3.bin"}
17:15:34.262 RSL: RESULT = {"OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32c3.bin"}
```

**Comment by Jason2866** [comment]
Oh, my. Shelly changed the default address for App partition 0. This is (was) until now 0x10000 for every project done with IDF, Arduino and whatever SDK was used.
Since esp32x code is running at every aligned address this can be easily done. Until now no one did.
@s-hadinger This is an unfortunate change. Looks like the script needs to check where app_0 slot is located. And do some more "transform dance"

**Comment by s-hadinger** [comment]
Oh boy. So you have a test Shelly firmware dump for me to try?

**Comment by tbrasser** [comment]
Anything I can do on the device to provide relevant info?

**Comment by s-hadinger** [comment]
A complete dump of the original Shelly firmware would be awesome

**Comment by tbrasser** [comment]
How would I do that? Do I need to find my soldering iron and serial cable?

**Comment by Jason2866** [comment]
@tbrasser Please try latest Autoconfig. Before remove every file in Tasmota Filesystem.

**Comment by tbrasser** [comment]
Unfortunately I can't get it to work, still seeing the offset error I had before on that same device, after removing all files from flash.
Also on a new one I end up with no Partition_Wizad showing up. (added a comment on my original issue on mgos32-to-tasmota32)

**Comment by Jason2866** [comment]
@tbrasser culprit found. There is a 32k limit when reading files with Berry (safeguard for not go overboard with free heap...) Will be changed to read 4k chunks.

**Comment by tbrasser** [comment]
It worked! Thanks!

**Comment by Jason2866** [comment]
Thx for the feedback.
