### ISSUE TITLE
pins for sonoff bridge pro seem to be wrong

### ISSUE THREAD

**Issue by gdanov** [tasmota/autoconf#38]
Tried to use pin 14 and 13 to drive relay. Figured out it actually controls the green led. Then after some more looking, realised the pins in the "configure module" and on the board don't match. On the board I see DIO8, 11 and 14 while in the module config I see GPIO 13,14 and 33.

Please advise if and how I can use custom pin.

**Comment by Jason2866** [comment]
Not a supported use case for this device.
