### ISSUE TITLE
Some settings in init.bat are not adopted.

### ISSUE THREAD

**Issue by Papablaubaer** [tasmota/autoconf#51]
Ich bastle an einer Lösung meine Tasmota32 Geräte in einem Rutsch zu konfigurieren. Dazu verwende ich eine eigene .autoconf.
Einige Einstellungen in der init.bat werden nicht übernommen, sie sind also nach dem Neustart des Geräts und Verarbeitung der init.bat wieder auf  Standardeinstellungen eingestellt.
Hier eine Liste der Einstellungen bei denen mir das aufgefallen ist.
Interlock
PowerCal
CurrentCal
VoltageCal.

I'm working on a solution to configure my Tasmota32 devices in one go. I use my own .autoconf for this.
Some settings in the init.bat are not adopted, so they are set back to the default settings after restarting the device and processing the init.bat.
Here is a list of the settings where I noticed this.
Interlock
PowerCal
CurrentCal
VoltageCal.

**Comment by Jason2866** [comment]
Settings forcing a restart will prevent applying the next settings in the init.bat
Beside the fact providing calib data is not very useful. Device will be measure wrong.
Every device needs it's own calibration data.
